SELECT * FROM TEACHER;
SELECT * FROM PULPIT;
SELECT * FROM SUBJECT;
--1
CREATE OR REPLACE PROCEDURE GET_TEACHERS(PCODE IN TEACHER.PULPIT%TYPE)
IS
BEGIN
    FOR row IN (SELECT * FROM TEACHER WHERE PULPIT = PCODE)
    LOOP
        DBMS_OUTPUT.PUT_LINE(row.TEACHER|| '' || row.TEACHER_NAME || ' ' || row.PULPIT_NAME || ' ' || row.SALARY || ' ' || row.BIRTHDAY);
    END LOOP;
END;

BEGIN
    GET_TEACHERS('ÈÑèÒ');
END;

--2
CREATE OR REPLACE FUNCTION GET_NUM_TEACHERS(PCODE IN TEACHER.PULPIT%TYPE)
RETURN NUMBER
IS
    num_teachers NUMBER;
BEGIN
    SELECT COUNT(*) INTO num_teachers FROM TEACHER WHERE PULPIT = PCODE;
    RETURN num_teachers;
END;

DECLARE
    num_teachers NUMBER;
BEGIN
    num_teachers := GET_NUM_TEACHERS('ÈÑèÒ');
    DBMS_OUTPUT.PUT_LINE('Number of teachers: ' || num_teachers);
END;

--3
CREATE OR REPLACE PROCEDURE GET_TEACHERS (FCODE IN FACULTY.FACULTY%TYPE)
IS
BEGIN
    FOR row IN (SELECT * FROM TEACHER T INNER JOIN PULPIT P 
    ON T.PULPIT = P.PULPIT WHERE FACULTY = FCODE)
    LOOP
        DBMS_OUTPUT.PUT_LINE(row.TEACHER_NAME || ' ' || row.FACULTY);
    END LOOP;
END;

BEGIN
    GET_TEACHERS('ÈÒ');
END;

CREATE OR REPLACE PROCEDURE GET_SUBJECTS(PCODE IN SUBJECT.PULPIT%TYPE)
IS
BEGIN
    FOR row IN (SELECT * FROM SUBJECT WHERE PULPIT = PCODE)
    LOOP
        DBMS_OUTPUT.PUT_LINE(row.SUBJECT || ' ' ||row.SUBJECT_NAME);
    END LOOP;
END;
   
BEGIN
    GET_SUBJECTS('ËÂ');
END;

--4
CREATE OR REPLACE FUNCTION GET_NUM_TEACHERS(FCODE IN FACULTY.FACULTY%TYPE)
RETURN NUMBER
IS
    num_teachers NUMBER;
BEGIN
    SELECT COUNT(*) INTO num_teachers FROM TEACHER T INNER JOIN PULPIT F ON T.PULPIT = F.PULPIT WHERE FACULTY = FCODE;
    RETURN num_teachers;
END;

DECLARE
    num_teachers NUMBER;
BEGIN
    num_teachers := GET_NUM_TEACHERS('ÈÒ');
    DBMS_OUTPUT.PUT_LINE('Number of teachers: ' || num_teachers);
END;

CREATE OR REPLACE FUNCTION GET_NUM_SUBJECTS(PCODE IN SUBJECT.PULPIT%TYPE)
RETURN NUMBER
IS
    num_subjects NUMBER;
BEGIN
    SELECT COUNT(*) INTO num_subjects FROM SUBJECT WHERE PULPIT = PCODE;
    RETURN num_subjects;
END;

DECLARE
        num_subjects NUMBER;
BEGIN 
    num_subjects := GET_NUM_SUBJECTS('ÎÕ');
    DBMS_OUTPUT.PUT_LINE('Number of subjects: ' || num_subjects);
END;

--5
CREATE OR REPLACE PACKAGE TEACHERS
AS
    PROCEDURE GET_TEACHERS(FCODE IN FACULTY.FACULTY%TYPE);
    PROCEDURE GET_SUBJECTS(PCODE IN SUBJECT.PULPIT%TYPE);
    FUNCTION GET_NUM_TEACHERS(FCODE FACULTY.FACULTY%TYPE) RETURN NUMBER;
    FUNCTION GET_NUM_SUBJECTS(PCODE IN SUBJECT.PULPIT%TYPE) RETURN NUMBER;
END TEACHERS;

--6
CREATE OR REPLACE PACKAGE BODY TEACHERS
IS
PROCEDURE GET_TEACHERS(FCODE IN FACULTY.FACULTY%TYPE)
IS
BEGIN
    FOR row IN (SELECT * FROM TEACHER T INNER JOIN PULPIT P 
    ON T.PULPIT = P.PULPIT WHERE FACULTY = FCODE)
    LOOP
        DBMS_OUTPUT.PUT_LINE(row.TEACHER_NAME || ' ' || row.FACULTY);
    END LOOP;
END GET_TEACHERS;

PROCEDURE GET_SUBJECTS(PCODE IN SUBJECT.PULPIT%TYPE)
IS
BEGIN
 FOR row IN (SELECT * FROM SUBJECT WHERE PULPIT = PCODE)
    LOOP
        DBMS_OUTPUT.PUT_LINE(row.SUBJECT || ' ' ||row.SUBJECT_NAME);
    END LOOP;
END GET_SUBJECTS;

FUNCTION GET_NUM_TEACHERS(FCODE FACULTY.FACULTY%TYPE)
RETURN NUMBER
IS
    num_teachers NUMBER;
BEGIN
    SELECT COUNT(*) INTO num_teachers FROM TEACHER T INNER JOIN PULPIT F ON T.PULPIT = F.PULPIT WHERE FACULTY = FCODE;
    RETURN num_teachers;
END GET_NUM_TEACHERS;

FUNCTION GET_NUM_SUBJECTS(PCODE IN SUBJECT.PULPIT%TYPE)
RETURN NUMBER
IS
    num_subjects NUMBER;
BEGIN
    SELECT COUNT(*) INTO num_subjects FROM SUBJECT WHERE PULPIT = PCODE;
    RETURN num_subjects;
END GET_NUM_SUBJECTS;
END TEACHERS;


DECLARE 
    num_teachers NUMBER;
    num_subjects NUMBER;
BEGIN
    TEACHERS.GET_TEACHERS('ÈÑèÒ');
    TEACHERS.GET_SUBJECTS('ËÂ');
    num_teachers := TEACHERS.GET_NUM_TEACHERS('ÈÒ');
    DBMS_OUTPUT.PUT_LINE('Number of teachers: ' || num_teachers);
    num_subjects := TEACHERS.GET_NUM_SUBJECTS('ÎÕ');
    DBMS_OUTPUT.PUT_LINE('Number of subjects: ' || num_subjects);
END;

COMMIT;