CREATE TABLESPACE TS_LVD
    DATAFILE 'C:\app\orcl_wald\Tablespace\TS_LVD.dbf'
    SIZE 7M
    AUTOEXTEND ON NEXT 5M
    MAXSIZE 30M
    EXTENT MANAGEMENT LOCAL;

DROP TABLESPACE TS_LVD;

CREATE TEMPORARY TABLESPACE TS_TEMP_LVD
    TEMPFILE 'C:\app\orcl_wald\Tablespace\TS_TEMP_LVD.dbf'
    SIZE 5M
    AUTOEXTEND ON NEXT 3M
    MAXSIZE 20M
    EXTENT MANAGEMENT LOCAL;

DROP TABLESPACE TS_TEMP_LVD;

SELECT TABLESPACE_NAME, STATUS, contents loggin from SYS.DBA_TABLESPACES;

SELECT FILE_NAME, TABLESPACE_NAME, STATUS, MAXBYTES, USER_BYTES FROM DBA_DATA_FILES
UNION
SELECT FILE_NAME, TABLESPACE_NAME, STATUS, MAXBYTES, USER_BYTES FROM DBA_TEMP_FILES;

alter session set "_ORACLE_SCRIPT"=true;
alter session set "_ORACLE_SCRIPT"=false;

CREATE ROLE RL_LVDCORE;

SELECT * fROM dba_roles WHERE ROLE LIKE 'RL%';
SELECT * fROM dba_roles;

DROP ROLE RL_LVDCORE;

GRANT CREATE SESSION,
    CREATE TABLE,
    CREATE VIEW,
    CREATE PROCEDURE TO RL_LVDCORE;

SELECT * FROM dba_sys_privs WHERE grantee = 'RL_LVDCORE';
SELECT * FROM dba_sys_privs;

CREATE PROFILE PF_LVDCOREE LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 3
    FAILED_LOGIN_ATTEMPTS 7
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    PASSWORD_GRACE_TIME DEFAULT
    CONNECT_TIME 180
    IDLE_TIME 30;
    
DROP PROFILE PF_LVDCORE;

SELECT * FROM dba_profiles WHERE PROFILE = 'PF_LVDCORE';
SELECT * FROM dba_profiles WHERE PROFILE = 'DEFAULT';

CREATE USER LVDCORE IDENTIFIED BY 12345
    DEFAULT TABLESPACE TS_LVD QUOTA UNLIMITED ON TS_LVD
    TEMPORARY TABLESPACE TS_TEMP_LVD
    PROFILE PF_LVDCORE
    ACCOUNT UNLOCK 
    PASSWORD EXPIRE;
    
ALTER USER LVDCORE QUOTA 2M ON TS_LVD;

GRANT RL_LVDCORE TO LVDCORE;

DROP USER LVDCORE;

SELECT USERNAME
FROM v$session
WHERE username IS NOT NULL
GROUP BY USERNAME;

SELECT username, account_status, lock_date FROM dba_users;

ALTER TABLESPACE TS_LVD
    OFFLINE;

ALTER TABLESPACE TS_LVD
    ONLINE;


