//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab9
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class EDITION
    {
        [Key]
        public int ID_EDITION { get; set; }
        public Nullable<int> ID_BOOK { get; set; }
        public Nullable<int> DATE_EDITION { get; set; }
        public Nullable<int> DATE_SURRENDER { get; set; }
        [ForeignKey("ID_BOOK")]
        public virtual BOOKS BOOKS { get; set; }
    }
}
